---
# -------------------------------------------- #
# IAM User Access and Secret Key Rotation #
# -------------------------------------------- #

  - name: Get ~/.aws/credentials
    fetch:
      src: "{{ dest_home_dir }}/.aws/credentials"
      dest: creds
      flat: yes
      fail_on_missing: yes

  - name: Run Python Rotation Script
    shell: python rotate.py | tee -a "{{ ansible_date_time.date }}_rotation.log"
    args:
      chdir: "{{ role_path }}/files/"
    delegate_to: 127.0.0.1
    register: logs

  - debug: var=logs.stdout_lines
  - debug: var=logs.stderr_lines

  - name: Put back rotated credentials
    copy:
      src: creds
      dest: "{{ dest_home_dir }}/.aws/credentials"
      owner: "{{ dest_owner }}"
      group: "{{ dest_group }}"
      mode: 0751
      backup: yes

  - name: Clean up temporary creds files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - creds
