---
# -------------------------------------------- #
# IAM User Access and Secret Key Rotation #
# -------------------------------------------- #

  - name: Get ~/.aws/credentials
    fetch:
      src: /var/lib/jenkins/.aws/credentials
      dest: /var/lib/jenkins/creds
      flat: yes
      fail_on_missing: yes

  - name: Run Python Rotation Script
    shell: python rotate.py | tee -a "/var/lib/jenkins/{{ ansible_date_time.date }}_rotation.log"
    args:
      chdir: "{{ role_path }}/files/"
    delegate_to: 127.0.0.1
    register: logs

  - debug: var=logs.stdout_lines
  - debug: var=logs.stderr_lines

  - name: Put back rotated credentials
    copy:
      src: /var/lib/jenkins/creds
      dest: /var/lib/jenkins/.aws/credentials
      owner: jenkins
      group: sudo
      mode: 0751
      backup: yes

  - name: Clean up temporary creds files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /var/lib/jenkins/creds
